<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;


class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $users = [
            [
            'fname' => 'Mahmoud',
            'lname' => 'Mohamed',
            'email' => 'mahmoud.muhamed94@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'cairo',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'admin',

        ],
        [
            'fname' => 'Mohamed',
            'lname' => 'Saad',
            'email' => 'mohamedsaad17878@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'alex',
            'street' => 'waleed',
            'phone' => 123456789,
            'role' => 'admin',
        ],
        [
            'fname' => 'Mahmoud',
            'lname' => 'Lebda',
            'email' => 'mahmodsaadlebda@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'tanta',
            'street' => 'ezz',
            'phone' => 123456789,
            'role' => 'admin',
        ],
        [
            'fname' => 'Basma',
            'lname' => 'Farok',
            'email' => 'basmafarouk05@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'alex',
            'street' => 'asfra',
            'phone' => 123456789,
            'role' => 'admin',
        ],
        [
            'fname' => 'Shrok',
            'lname' => 'Ayman',
            'email' => 'shrokayman99@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'cairo',
            'street' => 'manil',
            'phone' => 123456789,
            'role' => 'admin',
        ],
        [
            'fname' => 'Jim',
            'lname' => 'Carry',
            'email' => 'jim@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'new york',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'Will',
            'lname' => 'Smith',
            'email' => 'Will@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'florida',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'Jason',
            'lname' => 'Statham',
            'email' => 'jason@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'london',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'Dawyn',
            'lname' => 'Jhonson',
            'email' => 'dawyn@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'boston',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'Tom',
            'lname' => 'Cruse',
            'email' => 'tom@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'annie',
            'lname' => 'Cruse',
            'email' => 'annie@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'Tommie',
            'lname' => 'Cruse',
            'email' => 'tommie@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'messi',
            'lname' => 'Cruse',
            'email' => 'messi@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'kaka',
            'lname' => 'Cruse',
            'email' => 'kaka@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'ronaldo',
            'lname' => 'Cruse',
            'email' => 'ronaldo@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'nymar',
            'lname' => 'Cruse',
            'email' => 'nymar@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'mosala',
            'lname' => 'Cruse',
            'email' => 'mosala@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'hazard',
            'lname' => 'Cruse',
            'email' => 'hazard@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'alex',
            'lname' => 'Cruse',
            'email' => 'alex@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'henry',
            'lname' => 'Cruse',
            'email' => 'henry@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'pogaba',
            'lname' => 'Cruse',
            'email' => 'pogaba@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'ronaldinho',
            'lname' => 'Cruse',
            'email' => 'ronaldinho@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'robinho',
            'lname' => 'Cruse',
            'email' => 'robinho@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'drogba',
            'lname' => 'Cruse',
            'email' => 'drogba@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'mounir',
            'lname' => 'Cruse',
            'email' => 'mounir@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'diab',
            'lname' => 'Cruse',
            'email' => 'diab@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'tomas',
            'lname' => 'Cruse',
            'email' => 'tomas@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'hamaki',
            'lname' => 'Cruse',
            'email' => 'hamaki@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'hamoksha',
            'lname' => 'Cruse',
            'email' => 'hamoksha@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        [
            'fname' => 'john',
            'lname' => 'Cruse',
            'email' => 'john@gmail.com',
            'password' => bcrypt('123456'),
            'city' => 'califorina',
            'street' => 'khattab',
            'phone' => 123456789,
            'role' => 'user',
        ],
        ];

        DB::table('users')->insert($users);
    }
}
